// js/solid/src/YasTerminal.tsx
import {
  onMount,
  onCleanup,
  createEffect,
  createMemo,
  createSignal,
  type JSX,
} from "solid-js";
import { YasTerminalSurface } from "@yas-run/core";
import type { SessionId, TerminalPalette } from "@yas-run/core";
import { useYasContext, useRequiredYasWorkspace } from "./YasContext.js";
import { createYasWorkspaceState } from "./hooks/createYasWorkspace.js";

export interface YasTerminalProps {
  sessionId: SessionId | null;
  fontFamily?: string;
  fontSize?: number;
  class?: string;
  style?: JSX.CSSProperties;
  palette?: TerminalPalette;
  readOnly?: boolean;
  /** Resize the remote session to this surface. Disable for passive previews. Default: true. */
  resizable?: boolean;
  /** Scale and center a passive preview to fit its container width. Ignored while resizable. */
  fitWidth?: boolean;
  showCursor?: boolean;
  onRender?: (renderMs: number) => void;
  scrollbarColor?: string;
  scrollbarWidth?: number;
  advanceRatio?: number;
  /** Coverage gamma for glyph antialiasing: 1 leaves antialiasing untouched,
   *  above 1 thins light-on-dark text. Default: DEFAULT_TEXT_GAMMA. */
  textGamma?: number;
  /** Callback to receive the underlying YasTerminalSurface after mount. */
  surfaceRef?: (surface: YasTerminalSurface | null) => void;
}

/**
 * YasTerminal renders a yas terminal inside a WebGL canvas.
 *
 * This is a thin Solid wrapper over `YasTerminalSurface` from `@yas-run/core`.
 * It renders a container `<div>`, attaches the surface on mount, and uses
 * `createEffect` to forward reactive prop changes to the surface.
 */
export function YasTerminal(props: YasTerminalProps) {
  const ctx = useYasContext();
  const workspace = useRequiredYasWorkspace();
  const snapshot = createYasWorkspaceState(workspace);

  let containerRef!: HTMLDivElement;
  // Use a signal so that effects re-run when the surface is created in
  // onMount.  Without this, effects that run during component init see
  // `null` and never retry after the surface is attached.
  const [surface, setSurface] = createSignal<YasTerminalSurface | null>(null);
  // Cleanup must not write this reactive signal while Solid is disposing the
  // owner. Clear non-reactive ownership before dispose so synchronous parent
  // invalidation cannot dispose the same surface recursively.
  let ownedSurface: YasTerminalSurface | null = null;

  onMount(() => {
    const s = new YasTerminalSurface({
      sessionId: props.sessionId,
      fontFamily: props.fontFamily ?? ctx.fontFamily,
      fontSize: props.fontSize ?? ctx.fontSize,
      palette: props.palette ?? ctx.palette,
      readOnly: props.readOnly,
      resizable: props.resizable,
      fitWidth: props.fitWidth,
      showCursor: props.showCursor,
      onRender: props.onRender,
      scrollbarColor: props.scrollbarColor,
      scrollbarWidth: props.scrollbarWidth,
      advanceRatio: props.advanceRatio ?? ctx.advanceRatio,
      textGamma: props.textGamma ?? ctx.textGamma,
    });
    ownedSurface = s;
    s.setWorkspace(workspace);
    s.attach(containerRef);
    setSurface(s);
    props.surfaceRef?.(s);
  });

  onCleanup(() => {
    const s = ownedSurface;
    ownedSurface = null;
    props.surfaceRef?.(null);
    s?.dispose();
  });

  // Forward connection changes. Reading snapshot() inside createEffect makes
  // this reactive — it re-runs whenever the workspace snapshot changes
  // (connection status transitions, new sessions, etc.).
  createEffect(() => {
    const s = surface();
    const snap = snapshot();
    const session = props.sessionId
      ? (snap.sessions.find((ss) => ss.id === props.sessionId) ?? null)
      : null;
    const conn = session ? workspace.getConnection(session.connectionId) : null;
    s?.setConnection(conn);
  });

  // Forward prop changes.
  createEffect(() => surface()?.setSessionId(props.sessionId));
  createEffect(() => surface()?.setPalette(props.palette ?? ctx.palette));
  createEffect(() =>
    surface()?.setFontFamily(props.fontFamily ?? ctx.fontFamily),
  );
  createEffect(() => surface()?.setFontSize(props.fontSize ?? ctx.fontSize));
  createEffect(() => surface()?.setShowCursor(props.showCursor));
  createEffect(() => surface()?.setOnRender(props.onRender));
  createEffect(() =>
    surface()?.setAdvanceRatio(props.advanceRatio ?? ctx.advanceRatio),
  );
  createEffect(() => surface()?.setTextGamma(props.textGamma ?? ctx.textGamma));
  createEffect(() => surface()?.setReadOnly(props.readOnly));
  createEffect(() => surface()?.setResizable(props.resizable));
  createEffect(() => surface()?.setFitWidth(props.fitWidth));

  // Re-send dimensions only when this session's connection becomes ready.
  // Reading snapshot() directly in the effect made every unrelated workspace
  // update repeat CONFIGURE_VIEW, including terminal frames caused by the
  // preceding configure.
  const readySessionId = createMemo(() => {
    const snap = snapshot();
    const session = props.sessionId
      ? (snap.sessions.find((ss) => ss.id === props.sessionId) ?? null)
      : null;
    const connection = session
      ? (snap.connections.find((c) => c.id === session.connectionId) ?? null)
      : null;
    return connection?.status === "connected" ? props.sessionId : null;
  });
  createEffect(() => {
    const s = surface();
    if (readySessionId() !== null) s?.resendSize();
  });

  return (
    <div
      ref={containerRef}
      class={props.class}
      style={{
        position: "relative",
        overflow: "hidden",
        ...props.style,
      }}
    />
  );
}

// js/react/src/YasTerminal.tsx
import { useEffect, useImperativeHandle, useRef } from "react";
import type { Ref } from "react";
import type { ConnectionStatus } from "@yas-run/core";
import type { Terminal } from "@yas-run/browser";
import { YasTerminalSurface } from "@yas-run/core";
import type { YasTerminalProps } from "./types.js";
import { useYasContext, useRequiredYasWorkspace } from "./YasContext.js";
import { useYasConnection } from "./hooks/useYasConnection.js";
import { useYasSession } from "./hooks/useYasSession.js";

// ---------------------------------------------------------------------------
// Public handle exposed via ref
// ---------------------------------------------------------------------------

export interface YasTerminalHandle {
  /** The underlying WASM Terminal instance, if initialised. */
  terminal: Terminal | null;
  /** Current grid dimensions. */
  rows: number;
  cols: number;
  /** Current connection status. */
  status: ConnectionStatus;
  /** Focus the input sink so the terminal can receive keyboard events. */
  focus(): void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * YasTerminal renders a yas terminal inside a WebGL canvas.
 *
 * This is a thin wrapper over `YasTerminalSurface` from `@yas-run/core`.
 * It renders a container `<div>`, attaches the surface to it on mount,
 * and forwards prop changes to the surface's setters.
 */
export function YasTerminal({
  ref,
  ...props
}: YasTerminalProps & { ref?: Ref<YasTerminalHandle> }) {
  const ctx = useYasContext();
  const workspace = useRequiredYasWorkspace();
  const session = useYasSession(props.sessionId);
  const connection = useYasConnection(session?.connectionId);
  const yasConn = session
    ? workspace.getConnection(session.connectionId)
    : null;

  const {
    sessionId,
    fontFamily = ctx.fontFamily,
    fontSize = ctx.fontSize,
    className,
    style,
    palette = ctx.palette,
    readOnly,
    resizable,
    fitWidth,
    showCursor,
    onRender,
    scrollbarColor,
    scrollbarWidth,
    advanceRatio = ctx.advanceRatio,
    textGamma = ctx.textGamma,
  } = props;

  const containerRef = useRef<HTMLDivElement>(null);
  const surfaceRef = useRef<YasTerminalSurface | null>(null);

  // Create the surface once on mount.
  useEffect(() => {
    const surface = new YasTerminalSurface({
      sessionId,
      fontFamily,
      fontSize,
      palette,
      readOnly,
      resizable,
      fitWidth,
      showCursor,
      onRender,
      scrollbarColor,
      scrollbarWidth,
      advanceRatio,
      textGamma,
    });
    surfaceRef.current = surface;
    props.surfaceRef?.(surface);

    return () => {
      props.surfaceRef?.(null);
      surface.dispose();
      surfaceRef.current = null;
    };
    // Only create/destroy on mount/unmount. Props are forwarded via setters.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Attach/detach to the container div.
  useEffect(() => {
    const surface = surfaceRef.current;
    const container = containerRef.current;
    if (!surface || !container) return;
    surface.attach(container);
    return () => surface.detach();
  }, []);

  // Forward workspace + connection.
  useEffect(() => {
    surfaceRef.current?.setWorkspace(workspace);
  }, [workspace]);

  useEffect(() => {
    surfaceRef.current?.setConnection(yasConn);
  }, [yasConn]);

  // Forward all prop changes.
  useEffect(() => {
    surfaceRef.current?.setSessionId(sessionId);
  }, [sessionId]);

  useEffect(() => {
    surfaceRef.current?.setPalette(palette);
  }, [palette]);

  useEffect(() => {
    surfaceRef.current?.setFontFamily(fontFamily);
  }, [fontFamily]);

  useEffect(() => {
    surfaceRef.current?.setFontSize(fontSize);
  }, [fontSize]);

  useEffect(() => {
    surfaceRef.current?.setShowCursor(showCursor);
  }, [showCursor]);

  useEffect(() => {
    surfaceRef.current?.setOnRender(onRender);
  }, [onRender]);

  useEffect(() => {
    surfaceRef.current?.setAdvanceRatio(advanceRatio);
  }, [advanceRatio]);

  useEffect(() => {
    surfaceRef.current?.setTextGamma(textGamma);
  }, [textGamma]);

  useEffect(() => {
    surfaceRef.current?.setReadOnly(readOnly);
  }, [readOnly]);

  useEffect(() => {
    surfaceRef.current?.setResizable(resizable);
  }, [resizable]);

  useEffect(() => {
    surfaceRef.current?.setFitWidth(fitWidth);
  }, [fitWidth]);

  // Re-send dimensions when connection becomes ready.
  const status: ConnectionStatus = connection?.status ?? "disconnected";
  useEffect(() => {
    if (status === "connected" && sessionId !== null) {
      surfaceRef.current?.resendSize();
    }
  }, [status, sessionId]);

  // Imperative handle.
  useImperativeHandle(
    ref,
    () => ({
      get terminal() {
        return surfaceRef.current?.currentTerminal ?? null;
      },
      get rows() {
        return surfaceRef.current?.rows ?? 24;
      },
      get cols() {
        return surfaceRef.current?.cols ?? 80;
      },
      status,
      focus() {
        surfaceRef.current?.focus();
      },
    }),
    [status],
  );

  return (
    <div
      ref={containerRef}
      className={className}
      style={{
        position: "relative",
        overflow: "hidden",
        ...style,
      }}
    />
  );
}
